// Country list with country name, currency code, and flag country code (for FlagsAPI)
const countryList = [
    { name: "United States", code: "USD", country: "US", symbol: "$" },
    { name: "Eurozone", code: "EUR", country: "EU", symbol: "€" },
    { name: "United Kingdom", code: "GBP", country: "GB", symbol: "£" },
    { name: "Japan", code: "JPY", country: "JP", symbol: "¥" },
    { name: "Pakistan", code: "PKR", country: "PK", symbol: "₨" },
    { name: "India", code: "INR", country: "IN", symbol: "₹" },
    { name: "Canada", code: "CAD", country: "CA", symbol: "$" },
    { name: "Australia", code: "AUD", country: "AU", symbol: "$" },
    { name: "China", code: "CNY", country: "CN", symbol: "¥" },
    { name: "Saudi Arabia", code: "SAR", country: "SA", symbol: "﷼" },
    { name: "UAE", code: "AED", country: "AE", symbol: "د.إ" },
    { name: "Turkey", code: "TRY", country: "TR", symbol: "₺" },
    { name: "Russia", code: "RUB", country: "RU", symbol: "₽" },
    { name: "Brazil", code: "BRL", country: "BR", symbol: "R$" },
    { name: "South Africa", code: "ZAR", country: "ZA", symbol: "R" },
    { name: "Singapore", code: "SGD", country: "SG", symbol: "$" },
    { name: "Malaysia", code: "MYR", country: "MY", symbol: "RM" },
    { name: "Thailand", code: "THB", country: "TH", symbol: "฿" },
    { name: "Egypt", code: "EGP", country: "EG", symbol: "£" },
    { name: "Nigeria", code: "NGN", country: "NG", symbol: "₦" },
    { name: "Bangladesh", code: "BDT", country: "BD", symbol: "৳" },
    { name: "Switzerland", code: "CHF", country: "CH", symbol: "Fr" },
    { name: "Sweden", code: "SEK", country: "SE", symbol: "kr" },
    { name: "New Zealand", code: "NZD", country: "NZ", symbol: "$" },
    { name: "Mexico", code: "MXN", country: "MX", symbol: "$" },
    { name: "Norway", code: "NOK", country: "NO", symbol: "kr" },
    { name: "Denmark", code: "DKK", country: "DK", symbol: "kr" },
    { name: "Poland", code: "PLN", country: "PL", symbol: "zł" },
    { name: "Israel", code: "ILS", country: "IL", symbol: "₪" },
    { name: "Hong Kong", code: "HKD", country: "HK", symbol: "$" },
    { name: "Indonesia", code: "IDR", country: "ID", symbol: "Rp" },
    { name: "Philippines", code: "PHP", country: "PH", symbol: "₱" },
    { name: "South Korea", code: "KRW", country: "KR", symbol: "₩" },
    { name: "Czech Republic", code: "CZK", country: "CZ", symbol: "Kč" },
    { name: "Hungary", code: "HUF", country: "HU", symbol: "Ft" },
    { name: "Romania", code: "RON", country: "RO", symbol: "lei" },
    { name: "Chile", code: "CLP", country: "CL", symbol: "$" },
    { name: "Colombia", code: "COP", country: "CO", symbol: "$" },
    { name: "Argentina", code: "ARS", country: "AR", symbol: "$" },
    { name: "Vietnam", code: "VND", country: "VN", symbol: "₫" },
    { name: "Ukraine", code: "UAH", country: "UA", symbol: "₴" },
    { name: "Morocco", code: "MAD", country: "MA", symbol: "د.م." },
    { name: "Kenya", code: "KES", country: "KE", symbol: "KSh" },
    { name: "Ghana", code: "GHS", country: "GH", symbol: "₵" },
    { name: "Qatar", code: "QAR", country: "QA", symbol: "ر.ق" },
    { name: "Kuwait", code: "KWD", country: "KW", symbol: "د.ك" },
    { name: "Jordan", code: "JOD", country: "JO", symbol: "د.ا" },
    { name: "Oman", code: "OMR", country: "OM", symbol: "ر.ع." },
    { name: "Bahrain", code: "BHD", country: "BH", symbol: ".د.ب" },
    { name: "Sri Lanka", code: "LKR", country: "LK", symbol: "₨" },
    { name: "Nepal", code: "NPR", country: "NP", symbol: "₨" },
    { name: "Afghanistan", code: "AFN", country: "AF", symbol: "؋" },
    { name: "Uzbekistan", code: "UZS", country: "UZ", symbol: "so'm" },
    { name: "Kazakhstan", code: "KZT", country: "KZ", symbol: "₸" },
    { name: "Georgia", code: "GEL", country: "GE", symbol: "₾" },
    { name: "Azerbaijan", code: "AZN", country: "AZ", symbol: "₼" },
    { name: "Peru", code: "PEN", country: "PE", symbol: "S/." },
    { name: "Venezuela", code: "VES", country: "VE", symbol: "Bs.S" },
    { name: "Paraguay", code: "PYG", country: "PY", symbol: "₲" },
    { name: "Uruguay", code: "UYU", country: "UY", symbol: "$U" },
    { name: "Bolivia", code: "BOB", country: "BO", symbol: "Bs." },
    { name: "Costa Rica", code: "CRC", country: "CR", symbol: "₡" },
    { name: "Panama", code: "PAB", country: "PA", symbol: "B/." },
    { name: "Dominican Republic", code: "DOP", country: "DO", symbol: "RD$" },
    { name: "Jamaica", code: "JMD", country: "JM", symbol: "J$" },
    { name: "Trinidad and Tobago", code: "TTD", country: "TT", symbol: "TT$" },
    { name: "Algeria", code: "DZD", country: "DZ", symbol: "دج" },
    { name: "Tunisia", code: "TND", country: "TN", symbol: "د.ت" },
    { name: "Libya", code: "LYD", country: "LY", symbol: "ل.د" },
    { name: "Sudan", code: "SDG", country: "SD", symbol: "ج.س." },
    { name: "Ethiopia", code: "ETB", country: "ET", symbol: "Br" },
    { name: "Tanzania", code: "TZS", country: "TZ", symbol: "Sh" },
    { name: "Uganda", code: "UGX", country: "UG", symbol: "USh" },
    { name: "Zambia", code: "ZMW", country: "ZM", symbol: "ZK" },
    { name: "Botswana", code: "BWP", country: "BW", symbol: "P" },
    { name: "Mauritius", code: "MUR", country: "MU", symbol: "₨" },
    { name: "Seychelles", code: "SCR", country: "SC", symbol: "₨" },
    { name: "Maldives", code: "MVR", country: "MV", symbol: "Rf" },
    { name: "Fiji", code: "FJD", country: "FJ", symbol: "$" },
    { name: "Samoa", code: "WST", country: "WS", symbol: "WS$" },
    { name: "Papua New Guinea", code: "PGK", country: "PG", symbol: "K" }
    // Add more if needed
];

// Export for use in other scripts
if (typeof module !== "undefined") {
    module.exports = countryList;
}